// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
export const BUILD_INFO = {
  "commit": "6d260c13bf36",
  "branch": "claude/x-feed-redirect-feature-Mq8su",
  "dirty": true,
  "generatedAt": "2026-05-04T14:19:23.365Z"
}
