// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
export const BUILD_INFO = {
  "commit": "8fc61b8c6b61",
  "branch": "codex/quick-action-helper",
  "dirty": true,
  "generatedAt": "2026-03-05T14:19:09.127Z"
}
