// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
export const BUILD_INFO = {
  "commit": "8087be23e064",
  "branch": "claude/x-feed-redirect-feature-Mq8su",
  "dirty": true,
  "generatedAt": "2026-05-04T16:35:30.009Z"
}
